apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jmeter
      image: luiarhs/jmeter:latest # Your custom JMeter image
      command:
        - cat
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: "/home/jenkins/agent"
  volumes:
    - name: workspace-volume
      emptyDir: {}
