controller:
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"
    pullPolicy: "IfNotPresent"
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
  serviceType: NodePort
  servicePort: 8080
  nodePort: 30000  # Jenkins will be available on localhost:30000
  controller.admin.username: admin
  controller.admin.password: admin

  # Persistent Volume configuration
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""  # Leave empty to use Docker Desktop's default storage class
    accessMode: ReadWriteOnce

  # Add pod templates under JCasC (Jenkins Configuration as Code)
  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      podTemplates: |
        jenkins:
          clouds:
            - kubernetes:
                templates:
                  - name: "jmeter-agent"
                    label: "jmeter-agent"
                    containers:
                      - name: "jmeter"
                        image: "luiarhs/jmeter:latest"
                        command:
                          - "cat"  # Keeps the pod alive to execute Jenkins commands
                        workingDir: "/home/jenkins"
                        resourceRequestCpu: "500m"
                        resourceRequestMemory: "512Mi"
                        resourceLimitCpu: "1"
                        resourceLimitMemory: "1024Mi"

agent:
  enabled: false  # Disable the default Jenkins agent; we will use Kubernetes agents
